# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  
    config.vm.define "httpd" do |httpd|
    httpd.vm.network "private_network", ip: "192.168.10.12"
    httpd.vm.provision "ansible" do |ansible|
      ansible.playbook = "httpd/site.yml"
      ansible.extra_vars = {
        web_servers: [
		  {
            name: "one",
            port: 80,
            config_filename: "httpd1.conf"
          },
          {
            name: "two",
            port: 81,
            config_filename: "httpd1.conf"
          },
          {
            name: "three",
            port: 82,
            config_filename: "httpd1.conf"
          }
        ]
      }
    end
  end
end
